name: Generate Profile Metrics

on:
  schedule:
    - cron: "30 0 * * *" # daily 00:30 UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}

          filename: assets/metrics.svg
          config_timezone: Asia/Colombo

          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          config_display: large
          config_padding: 14%
          config_border_radius: 14
          config_output: svg

          config_order: base.header, base.activity, plugin.languages, base.repositories, base.community, base.metadata

          config_twemoji: yes

          config_gemoji: yes

          config_base64: no

          config_theme: dark
          config_background: 0c0c0e
          config_color: d4d4d8
          config_color2: ea580c
          config_color3: f97316
          config_color4: 38bdf8
          config_color5: a1a1aa
